//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using Microsoft.Extensions.Configuration;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BreweryManagementEntities : DbContext
    {
        public BreweryManagementEntities(IConfiguration configuration)
             : base(configuration.GetConnectionString("BreweryManagementEntities"))
        {
        }

        public BreweryManagementEntities()
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Beer> Beers { get; set; }
        public virtual DbSet<Brewer> Brewers { get; set; }
        public virtual DbSet<Brewery> Breweries { get; set; }
        public virtual DbSet<WholeSaler> WholeSalers { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
    }
}
